query Search ($q: SearchQuery!, $offset: Int!, $limit: PaginationLimit!) {
    search(q: $q) {
        hitcount
        works(offset: $offset, limit: $limit) {
          manifestations {
            first {
              cover {
                detail
                
              }
            }
          }
          titles {
            main
          }
          creators {
            display
          }
          subjects {
            dbcVerified {
              display
            }
          }
        }
      }
  }


  query Suggestion($q: String!, $worktype: WorkType, $suggesttype: SuggestionType) {
  suggest(q: $q, workType: $worktype, suggestType: $suggesttype) {
    result {
      type
      work {
      
      workId
        titles {
          main
        }
        creators {
          display
        }
        manifestations {
          first {
            cover {
              detail
            }
          }
        }
      }
    }
  }
}

query getWork($id: String!) {
  work(id: $id) {
    subjects {
      all {

        display
      }
    }
    workId
    titles {
      full
    }
    abstract
    creators {
      display
    }
    subjects {
      dbcVerified {
        display
      }
    }
    workYear
    workTypes
    mainLanguages {
      display
    }
    manifestations {
      first {
        cover {
          detail
        }
      }
    }
  }
}


#query getFrontPage { 
#  nodeQuery(
#    filter: {conditions: [{field: "type", value: ["hero_frontpage"]}, {field: "status", value: "1"}]}
#    sort: [{field: "changed", direction: DESC}]
#  ) {
#    entities {
#      
#      NodeHeroFrontpage {
#       nid
#       title
#       entityPublished
#       fieldHeroDescription
#        fieldImage {
#         alt
#         title
#         url
#         width
#         height
#       }
#      }
#   }
#  }
#}
query kasper($id: String!) {
  work(id: $id) {
    subjects {
      all {

        display
      }
    }
    workId
    titles {
      full
    }
    abstract
    creators {
      display
    }
    subjects {
      dbcVerified {
        display
      }
    }
    workYear
    workTypes
    mainLanguages {
      display
    }
    manifestations {
      first {
        cover {
          detail
        }
      }
    }
  }
}